### ISSUE TITLE
Wrong thumbnails displayed for neuropils

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/uk.ac.vfb.geppetto#13]
Wrong thumbnails showing up for neuropils

e.g.
![image](https://cloud.githubusercontent.com/assets/112839/18666403/96a92092-7f23-11e6-9da8-4f09b3e29d53.png)

Should be showing thumbnails of LAL - instead is showing thumbnails of neurons (in LAL?)

(Tested on http://vfbsandbox.inf.ed.ac.uk/)

**Comment by Robbie1977** [comment]
Resolved for all ( http://vfbsandbox.inf.ed.ac.uk/)
