### ISSUE TITLE
Add template as supertype for individuals

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/uk.ac.vfb.geppetto#3]
BG template query:

```
MATCH (i:Individual)-[:INSTANCEOF]-(:Class { short_form: 'image' }),(a:Individual:VFB {short_form:'VFB_00000001'})<-[r1:Related { short_form : 'depicts' }]-(sc:Individual)-[r2]-(i:Individual)-[r3]-(bc:Individual) RETURN bc.short_form as id, bc.label as label limit 1;
```

**Comment by dosumis** [comment]
Don't understand how the title of this ticket related to the query in comments.

**Comment by dosumis** [comment]
Supertype for individuals can be reached via [:INSTANCEOF] edge.

**Comment by dosumis** [comment]
BTW - Probably don't want to expose channel and image individuals via TermInfo.

**Comment by Robbie1977** [comment]
the supertype isn't used in terminfo and only using the template id and label

**Comment by Robbie1977** [comment]
the query could probably be trimmed down a tad - just a reminder to add the query

**Comment by dosumis** [comment]
Think I can now guess what you're referring to.  You want template as a classification in OWL/neo?

So you could find all templates via: 

(i:Individual)-[:INSTANCEOF]-(:Class { label : 'template' }) RETURN i

??

This should also work:

(i:Individual)-[:Related { label: 'has_background_channel'})-(:Individual)-[:INSTANCEOF]-(:Class { short_form: 'image' })

**Comment by dosumis** [comment]
Only templates are used as background channels.  Right now, the template itself is classified as a channel (or will be once I bring the LMB DB up to date).  I avoided a 'has_template' relation as this only applies to registered data  - e.g. not to unregistered EM.

**Comment by Robbie1977** [comment]
I only need the template for each individual:

```
MATCH (a:Individual:VFB {short_form:'VFB_00000001'})<-[r1:Related { short_form : 'depicts' }]-(sc:Individual)-[r2]-(i:Individual)-[r3]-(bc:Individual) RETURN bc.short_form as id, bc.label as label limit 1;
```

gives me that, not sure it could be made any smaller.

**Comment by Robbie1977** [comment]
Geppetto just needs some sort of sanity check that the data it's loading is in the same space hence giving it a supertype for the template

**Comment by dosumis** [comment]
> Geppetto just needs some sort of sanity check that the data it's loading is in the same space hence giving it a supertype for the template

OK.  That's exactly what the new structure is for.  I'm just a bit confused by your terminology 'template as a supertype for individuals'.  Supertype for individual suggests some kind of classification of an individual to me.  Images and channels are also individuals in OWL/neo & these have their own classifications.    What you want is the template(s) available for any _anatomical_ individual.

**Comment by Robbie1977** [comment]
I need to know for all individuals as if they belong to a different template we can't just overlay the image data.

To be clear I'm not requesting any changes to the Neo4j or OWL structure.

**Comment by dosumis** [comment]
Yep.  Understood that (at least by my last comment).  Just a good example of why standardising terminology will help us communicate.
