### ISSUE TITLE
Failure to launch 3D from VFB 1.5

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/uk.ac.vfb.geppetto#5]
Attempted launch of VFB 2.0 from sandbox3 via 3D=> the following error:

org.geppetto.core.common.GeppettoInitializationException: Unable to unmarshall simulation with url: http://vfbsandbox3.inf.ed.ac.uk/do/geppettoXml.xml?t=VFBt_001&i=VFB_00011319,VFB_00009437,VFB_00009455,VFB_00009456,VFB_00009457,VFB_00009461,VFB_00011205,VFB_00011207,VFB_00001756,VFB_00001747,VFB_00015975,VFB_00015994,VFB_00016138,VFB_00012942,VFB_00007950,VFB_00015379,VFB_00008537

**Comment by Robbie1977** [comment]
http://vfbsandbox3.inf.ed.ac.uk:8180/org.geppetto.frontend/geppetto?load_project_from_url=http://vfbsandbox3.inf.ed.ac.uk/do/geppettoJson.json?i=VFB_00011319,VFB_00009437,VFB_00009455,VFB_00009456,VFB_00009457,VFB_00009461,VFB_00011205,VFB_00011207,VFB_00001756,VFB_00001747,VFB_00015975,VFB_00015994,VFB_00016138,VFB_00012942,VFB_00007950,VFB_00015379,VFB_00008537%26t=VFBt_001%26d=

![image](https://cloud.githubusercontent.com/assets/4630768/16615863/5ff66278-4371-11e6-975c-e6b475f55c6e.png)

Is working this end. Can you paste your actual url the browser is loading?

**Comment by dosumis** [comment]
Doesn't work: 

![image](https://cloud.githubusercontent.com/assets/112839/16617692/0136c15e-437d-11e6-820c-2e9f7fb3d0b7.png)

**Comment by Robbie1977** [comment]
That makes more sense - I'm awaiting the port being opened for the geppetto server, went in yesterday afternoon so should be any minute now.

You can VPN to test until then

**Comment by Robbie1977** [comment]
Also you could use the old test server: so just replace vfbsandbox3.inf.ed.ac.uk:8180 with eccles.inf.ed.ac.uk:8084

**Comment by Robbie1977** [comment]
that explains the original fault as eccles is failing as it's expecting a dev build and the new version is master. It breaks the ecore if the ref doesn't match at the begining of the xmi/xml file
