### ISSUE TITLE
Display new split label in term info

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/uk.ac.vfb.geppetto#68]
See label from VirtualFlyBrain/VFB_neo4j#137

**Comment by dosumis** [comment]
Blocked by loading speed issues.

Need to add test with limit for VFB_neo4j : https://github.com/VirtualFlyBrain/VFB_neo4j/issues/150

- with that passing can merge and test with full build.  Full test loading should move to  Jenkins so  that we don't time out on Travis.
